select * from customer limit 20

-- 1. what is the total revenue generated by male vs fmale customers?
select gender, sum(purchase_amount) as revenue
from customer 
group by gender 
-- 2. which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- 3. which are the top5 products with the highest average review rating?
select item_purchas
-- 4. Compare the average purchase amounts between standard and express shipping.
-- 5. do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
-- 6. which 5 products have the highest percentsge of purchases with discount applied?
-- 7. segment customers into new, returning, and loyal based on their total number of previous purchase, and show the count of each segment.
-- 8. what are the top 3 most purchased products within each category?
-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- 10. what is the revenue contribution of each age group? 